//================================================================================================
// <auto-generated>
// This code was generated by a tool on machine OWL at local time 29/05/2025 11:58:40.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//================================================================================================
using System.CodeDom.Compiler;
using System.Net;
using System.Threading.Tasks;
using RCS.Licensing.Example.WebService.Shared;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RCS.Azure.StorageAccount.Shared;
using RCS.Licensing.Provider.Shared;
using RCS.Licensing.Provider.Shared.Entities;
using Swashbuckle.AspNetCore.Annotations;

#nullable enable

namespace RCS.Licensing.Example.WebService.Controllers;

partial class AuthenticationController
{
	/// <summary>
	///   Authenticate licensing system account Name and password credentials.
	/// </summary>
	/// <param name="request">The request body contains a serialized <c>LoginNameRequest</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>LicenceFull</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPost]
	[AllowAnonymous]
	[Route("name")]
	[ProducesResponseType(typeof(ResponseWrap<LicenceFull>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<LicenceFull>))]
	public async Task<ResponseWrap<LicenceFull>> AuthenticateName([FromBody] LoginNameRequest request)
	{
		return await InnerAuthenticateName(request);
	}

	/// <summary>
	///   Authenticate licensing system account Id and password credential authentication.
	/// </summary>
	/// <param name="request">A serialized <c>LoginIdRequest</c> in the request body.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>LicenceFull</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPost]
	[AllowAnonymous]
	[Route("id")]
	[ProducesResponseType(typeof(ResponseWrap<LicenceFull>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<LicenceFull>))]
	public async Task<ResponseWrap<LicenceFull>> AuthenticateId(LoginIdRequest request)
	{
		return await InnerAuthenticateId(request);
	}

}

partial class ServiceController
{
	/// <summary>
	///   Gets service metadata information.
	/// </summary>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>ServiceInfo</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpGet]
	[AllowAnonymous]
	[Route("info")]
	[ProducesResponseType(typeof(ResponseWrap<ServiceInfo>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<ServiceInfo>))]
	public async Task<ResponseWrap<ServiceInfo>> GetServiceInfo()
	{
		return await InnerGetServiceInfo();
	}

	/// <summary>
	///   Causes a deliberate service internal error for testing.
	/// </summary>
	/// <param name="number">Some number.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>MockResponse</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpGet]
	[AllowAnonymous]
	[Route("throw")]
	[ProducesResponseType(typeof(ResponseWrap<MockResponse>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<MockResponse>))]
	public async Task<ResponseWrap<MockResponse>> ThrowError([FromRoute] int number)
	{
		return await InnerThrowError(number);
	}

}

partial class ProviderController
{
	/// <summary>
	///   Gets a flag indicating if the licensing service provider supports realms.
	/// </summary>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>bool</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpGet]
	[AllowAnonymous]
	[Route("property/supportsrealms")]
	[ProducesResponseType(typeof(ResponseWrap<bool>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<bool>))]
	public async Task<ResponseWrap<bool>> GetSupportsRealms()
	{
		return await InnerGetSupportsRealms();
	}

	/// <summary>
	///   Gets the navigation tree.
	/// </summary>
	/// <remarks>
	///   Client applications can use the returned values to build custom navigation collections.
	/// </remarks>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>NavData</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpGet]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("navdata")]
	[ProducesResponseType(typeof(ResponseWrap<NavData>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<NavData>))]
	public async Task<ResponseWrap<NavData>> GetNavigationData()
	{
		return await InnerGetNavigationData();
	}

	/// <summary>
	///   Gets the database report.
	/// </summary>
	/// <remarks>
	///   Client applications can use the returned items to build custom reports.
	/// </remarks>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>ReportItem[]</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpGet]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("dbreport")]
	[ProducesResponseType(typeof(ResponseWrap<ReportItem[]>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<ReportItem[]>))]
	public async Task<ResponseWrap<ReportItem[]>> GetDatabaseReport()
	{
		return await InnerGetDatabaseReport();
	}

}

partial class RealmController
{
	/// <summary>
	///   Reads a realm by Id.
	/// </summary>
	/// <remarks>
	///   The response <c>hasError</c> property will be true if the realm is not found.
	/// </remarks>
	/// <param name="id">The Id of the realm to read.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>Realm?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpGet]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("read/{id}")]
	[ProducesResponseType(typeof(ResponseWrap<Realm?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<Realm?>))]
	public async Task<ResponseWrap<Realm?>> ReadRealm([FromRoute] string id)
	{
		return await InnerReadRealm(id);
	}

	/// <summary>
	///   Lists all realms.
	/// </summary>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>Realm[]</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpGet]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("list")]
	[ProducesResponseType(typeof(ResponseWrap<Realm[]>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<Realm[]>))]
	public async Task<ResponseWrap<Realm[]>> ListRealms()
	{
		return await InnerListRealms();
	}

	/// <summary>
	///   Updates or inserts a customer.
	/// </summary>
	/// <remarks>
	///   If the <c>Id</c> property is null then a new realm record is created, otherwise an existing realm with the Id is updated. The following properties are ignored: <c>Created</c>, <c>Customers</c>, <c>Users</c>.
	/// </remarks>
	/// <param name="realm">The request body contains a serialized <c>Realm</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>UpsertResult&lt;Realm&gt;</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPut]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("")]
	[ProducesResponseType(typeof(ResponseWrap<UpsertResult<Realm>>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<UpsertResult<Realm>>))]
	public async Task<ResponseWrap<UpsertResult<Realm>>> UpsertRealm([FromBody] Realm realm)
	{
		return await InnerUpsertRealm(realm);
	}

	/// <summary>
	///   Validates the properties of a realm.
	/// </summary>
	/// <param name="realmId">The Id of the parent realm to validate.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>string[]?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpGet]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("validate/{realmId}")]
	[ProducesResponseType(typeof(ResponseWrap<string[]?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<string[]?>))]
	public async Task<ResponseWrap<string[]?>> ValidateRealm([FromRoute] string realmId)
	{
		return await InnerValidateRealm(realmId);
	}

	/// <summary>
	///   Deletes a realm by Id.
	/// </summary>
	/// <remarks>
	///   The response integer is the number of licensing database rows affected by delete processing. Zero indicates that the realm was not found.
	/// </remarks>
	/// <param name="id">The Id of the realm to delete.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>int</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpDelete]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("{id}")]
	[ProducesResponseType(typeof(ResponseWrap<int>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<int>))]
	public async Task<ResponseWrap<int>> DeleteRealm([FromRoute] string id)
	{
		return await InnerDeleteRealm(id);
	}

	/// <summary>
	///   Disconnect a realm from a customer.
	/// </summary>
	/// <param name="realmId">The Id of the parent realm.</param>
	/// <param name="customerId">The Id of the child customer.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>Realm?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpGet]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("disconnect/{realmId}/customer/{customerId}")]
	[ProducesResponseType(typeof(ResponseWrap<Realm?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<Realm?>))]
	public async Task<ResponseWrap<Realm?>> DisconnectRealmChildCustomer([FromRoute] string realmId, [FromRoute] string customerId)
	{
		return await InnerDisconnectRealmChildCustomer(realmId, customerId);
	}

	/// <summary>
	///   Connects a realm to customers.
	/// </summary>
	/// <param name="request">The request body contains a serialized <c>JoinsRequest</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>Realm?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPost]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("connect/customers")]
	[ProducesResponseType(typeof(ResponseWrap<Realm?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<Realm?>))]
	public async Task<ResponseWrap<Realm?>> ConnectRealmChildCustomers([FromBody] JoinsRequest request)
	{
		return await InnerConnectRealmChildCustomers(request);
	}

	/// <summary>
	///   Replaces the joins between a realm and customers.
	/// </summary>
	/// <param name="request">The request body contains a serialized <c>JoinsRequest</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>Realm?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPost]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("replace/customers")]
	[ProducesResponseType(typeof(ResponseWrap<Realm?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<Realm?>))]
	public async Task<ResponseWrap<Realm?>> ReplaceRealmChildCustomers([FromBody] JoinsRequest request)
	{
		return await InnerReplaceRealmChildCustomers(request);
	}

	/// <summary>
	///   Disconnect a realm from a user.
	/// </summary>
	/// <param name="realmId">The Id of the parent realm.</param>
	/// <param name="userId">The Id of the child user.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>Realm?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpGet]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("disconnect/{realmId}/user/{userId}")]
	[ProducesResponseType(typeof(ResponseWrap<Realm?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<Realm?>))]
	public async Task<ResponseWrap<Realm?>> DisconnectRealmChildUser([FromRoute] string realmId, [FromRoute] string userId)
	{
		return await InnerDisconnectRealmChildUser(realmId, userId);
	}

	/// <summary>
	///   Connects a realm to users.
	/// </summary>
	/// <param name="request">The request body contains a serialized <c>JoinsRequest</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>Realm?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPost]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("connect/users")]
	[ProducesResponseType(typeof(ResponseWrap<Realm?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<Realm?>))]
	public async Task<ResponseWrap<Realm?>> ConnectRealmChildUsers([FromBody] JoinsRequest request)
	{
		return await InnerConnectRealmChildUsers(request);
	}

	/// <summary>
	///   Replaces the joins between a realm and users.
	/// </summary>
	/// <param name="request">The request body contains a serialized <c>JoinsRequest</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>Realm?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPost]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("replace/users")]
	[ProducesResponseType(typeof(ResponseWrap<Realm?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<Realm?>))]
	public async Task<ResponseWrap<Realm?>> ReplaceRealmChildUsers([FromBody] JoinsRequest request)
	{
		return await InnerReplaceRealmChildUsers(request);
	}

}

partial class CustomerController
{
	/// <summary>
	///   Lists all customers.
	/// </summary>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>Customer[]</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpGet]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("list")]
	[ProducesResponseType(typeof(ResponseWrap<Customer[]>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<Customer[]>))]
	public async Task<ResponseWrap<Customer[]>> ListCustomers()
	{
		return await InnerListCustomers();
	}

	/// <summary>
	///   Gets a summary list of customers filtered by realm.
	/// </summary>
	/// <param name="request">The request body contains a serialized <c>IdFilterRequest</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>Customer[]</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPost]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("list")]
	[ProducesResponseType(typeof(ResponseWrap<Customer[]>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<Customer[]>))]
	public async Task<ResponseWrap<Customer[]>> ListCustomers([FromBody] IdFilterRequest request)
	{
		return await InnerListCustomers(request);
	}

	/// <summary>
	///   Gets a summary pick list of all customers filterd by realm Id.
	/// </summary>
	/// <remarks>
	///   The returned array of lightweight <c>CustomerPick</c> objects can be used by clients to fill summary or pick lists of customers.
	/// </remarks>
	/// <param name="request">The request body contains a serialized <c>IdFilterRequest</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>CustomerPick[]</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPost]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("list/picks")]
	[ProducesResponseType(typeof(ResponseWrap<CustomerPick[]>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<CustomerPick[]>))]
	public async Task<ResponseWrap<CustomerPick[]>> ListCustomerPicksForRealms([FromBody] IdFilterRequest request)
	{
		return await InnerListCustomerPicksForRealms(request);
	}

	/// <summary>
	///   Updates or inserts a customer.
	/// </summary>
	/// <remarks>
	///   If the <c>Id</c> property is null then a new customer record is created, otherwise an existing customer with the Id is updated. The following properties are ignored: <c>Jobs</c>, <c>Realms</c>, <c>Users</c>.
	/// </remarks>
	/// <param name="customer">The request body contains a serialized <c>Customer</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>UpsertResult&lt;Customer&gt;</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPut]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("")]
	[ProducesResponseType(typeof(ResponseWrap<UpsertResult<Customer>>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<UpsertResult<Customer>>))]
	public async Task<ResponseWrap<UpsertResult<Customer>>> UpsertCustomer([FromBody] Customer customer)
	{
		return await InnerUpsertCustomer(customer);
	}

	/// <param name="id">The Id of the customer to validate.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>string[]</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpGet]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("validate/{id}")]
	[ProducesResponseType(typeof(ResponseWrap<string[]>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<string[]>))]
	public async Task<ResponseWrap<string[]>> ValidateCustomer([FromRoute] string id)
	{
		return await InnerValidateCustomer(id);
	}

	/// <summary>
	///   Deletes a customer by Id.
	/// </summary>
	/// <remarks>
	///   The response integer is the number of licensing database rows affected by delete processing. Zero indicates that the customer was not found.
	/// </remarks>
	/// <param name="id">The Id of the customer to delete.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>int</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpDelete]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("{id}")]
	[ProducesResponseType(typeof(ResponseWrap<int>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<int>))]
	public async Task<ResponseWrap<int>> DeleteCustomer([FromRoute] string id)
	{
		return await InnerDeleteCustomer(id);
	}

	/// <summary>
	///   Reads a customer by Id.
	/// </summary>
	/// <remarks>
	///   The response <c>hasError</c> property will be true if the customer is not found.
	/// </remarks>
	/// <param name="id">The Id of the customer to read.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>Customer?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// <br/><br/><b>Response Codes</b><br/>
	/// <br/>• 1 – Customer not found.
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpGet]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("read/{id}")]
	[ProducesResponseType(typeof(ResponseWrap<Customer?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<Customer?>))]
	public async Task<ResponseWrap<Customer?>> ReadCustomer([FromRoute] string id)
	{
		return await InnerReadCustomer(id);
	}

	/// <summary>
	///   Reads customers by Name.
	/// </summary>
	/// <param name="name">The name of the customers to read.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>Customer[]</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpGet]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("read/name/{name}")]
	[ProducesResponseType(typeof(ResponseWrap<Customer[]>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<Customer[]>))]
	public async Task<ResponseWrap<Customer[]>> ReadCustomersByName([FromRoute] string name)
	{
		return await InnerReadCustomersByName(name);
	}

	/// <summary>
	///   Disconnect a customer from a job.
	/// </summary>
	/// <param name="CustomerId">The Id of the parent customer.</param>
	/// <param name="jobId">The Id of the child job.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>Customer?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpGet]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("disconnect/{customerId}/job/{jobId}")]
	[ProducesResponseType(typeof(ResponseWrap<Customer?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<Customer?>))]
	public async Task<ResponseWrap<Customer?>> DisconnectCustomerChildJob([FromRoute] string CustomerId, [FromRoute] string jobId)
	{
		return await InnerDisconnectCustomerChildJob(CustomerId, jobId);
	}

	/// <summary>
	///   Connect a customer to jobs.
	/// </summary>
	/// <param name="request">The request body contains a serialized <c>JoinsRequest</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>Customer?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// <br/><br/><b>Response Codes</b><br/>
	/// <br/>• 1 – Customer not found.
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPost]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("connect/jobs")]
	[ProducesResponseType(typeof(ResponseWrap<Customer?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<Customer?>))]
	public async Task<ResponseWrap<Customer?>> ConnectCustomerChildJobs([FromBody] JoinsRequest request)
	{
		return await InnerConnectCustomerChildJobs(request);
	}

	/// <summary>
	///   Replaces the full set of customer jobs relations.
	/// </summary>
	/// <param name="request">The request body contains a serialized <c>JoinsRequest</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>Customer?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// <br/><br/><b>Response Codes</b><br/>
	/// <br/>• 1 – Customer not found.
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPost]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("replace/jobs")]
	[ProducesResponseType(typeof(ResponseWrap<Customer?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<Customer?>))]
	public async Task<ResponseWrap<Customer?>> ReplaceCustomerChildJobs([FromBody] JoinsRequest request)
	{
		return await InnerReplaceCustomerChildJobs(request);
	}

	/// <summary>
	///   Disconnect a customer from a user.
	/// </summary>
	/// <param name="customerId">The Id of the parent customer.</param>
	/// <param name="userId">The Id of the child user.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>Customer?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// <br/><br/><b>Response Codes</b><br/>
	/// <br/>• 1 – Customer not found.
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpGet]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("disconnect/{customerId}/user/{userId}")]
	[ProducesResponseType(typeof(ResponseWrap<Customer?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<Customer?>))]
	public async Task<ResponseWrap<Customer?>> DisconnectCustomerChildUser([FromRoute] string customerId, [FromRoute] string userId)
	{
		return await InnerDisconnectCustomerChildUser(customerId, userId);
	}

	/// <summary>
	///   Connect a customer to users.
	/// </summary>
	/// <param name="request">The request body contains a serialized <c>JoinsRequest</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>Customer?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPost]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("connect/users")]
	[ProducesResponseType(typeof(ResponseWrap<Customer?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<Customer?>))]
	public async Task<ResponseWrap<Customer?>> ConnectCustomerChildUsers([FromBody] JoinsRequest request)
	{
		return await InnerConnectCustomerChildUsers(request);
	}

	/// <summary>
	///   Replaces the full set of customer to user connections.
	/// </summary>
	/// <param name="request">The request body contains a serialized <c>JoinsRequest</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>Customer?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// <br/><br/><b>Response Codes</b><br/>
	/// <br/>• 1 – Customer not found.
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPost]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("replace/users")]
	[ProducesResponseType(typeof(ResponseWrap<Customer?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<Customer?>))]
	public async Task<ResponseWrap<Customer?>> ReplaceCustomerChildUsers([FromBody] JoinsRequest request)
	{
		return await InnerReplaceCustomerChildUsers(request);
	}

	/// <summary>
	///   Lists all Storage Accounts in the Azure Subscription associated with this web sersvice.
	/// </summary>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>SubscriptionAccount[]</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpGet]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("azure/storage/list")]
	[ProducesResponseType(typeof(ResponseWrap<SubscriptionAccount[]>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<SubscriptionAccount[]>))]
	public async Task<ResponseWrap<SubscriptionAccount[]>> ListStorageAccounts()
	{
		return await InnerListStorageAccounts();
	}

	/// <summary>
	///   Checks if a Storage Account name is globally available.
	/// </summary>
	/// <param name="name">The name of the Storage Account to check.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>bool?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpGet]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("azure/storage/available/{name}")]
	[ProducesResponseType(typeof(ResponseWrap<bool?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<bool?>))]
	public async Task<ResponseWrap<bool?>> IsStorageAccountNameAvailable([FromRoute] string name)
	{
		return await InnerIsStorageAccountNameAvailable(name);
	}

	/// <summary>
	///   Creates a Storage Account.
	/// </summary>
	/// <param name="request">The request body contains a serialized <c>CreateStorageAccountRequest</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>SubscriptionAccount?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPost]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("azure/storage")]
	[ProducesResponseType(typeof(ResponseWrap<SubscriptionAccount?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<SubscriptionAccount?>))]
	public async Task<ResponseWrap<SubscriptionAccount?>> CreateStorageAccount([FromBody] CreateStorageAccountRequest request)
	{
		return await InnerCreateStorageAccount(request);
	}

}

partial class JobController
{
	/// <summary>
	///   Reads a job by Id.
	/// </summary>
	/// <remarks>
	///   The response <c>hasError</c> property will be true if the job is not found.
	/// </remarks>
	/// <param name="id">The Id of the job to read.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>Job?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpGet]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("read/{id}")]
	[ProducesResponseType(typeof(ResponseWrap<Job?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<Job?>))]
	public async Task<ResponseWrap<Job?>> ReadJob([FromRoute] string id)
	{
		return await InnerReadJob(id);
	}

	/// <summary>
	///   Lists all jobs.
	/// </summary>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>Job[]</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpGet]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("list")]
	[ProducesResponseType(typeof(ResponseWrap<Job[]>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<Job[]>))]
	public async Task<ResponseWrap<Job[]>> ListJobs()
	{
		return await InnerListJobs();
	}

	/// <summary>
	///   Updates or inserts a job.
	/// </summary>
	/// <remarks>
	///   If the <c>Id</c> property is null then a new job record is created, otherwise an existing job with the Id is updated. The following properties are ignored: <c>Created</c>, <c>Users</c>.
	/// </remarks>
	/// <param name="job">The request body contains a serialized <c>Job</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>UpsertResult&lt;Job&gt;</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPut]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("")]
	[ProducesResponseType(typeof(ResponseWrap<UpsertResult<Job>>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<UpsertResult<Job>>))]
	public async Task<ResponseWrap<UpsertResult<Job>>> UpsertJob([FromBody] Job job)
	{
		return await InnerUpsertJob(job);
	}

	/// <param name="id">The Id of the job to validate.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>string[]</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpGet]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("validate/{id}")]
	[ProducesResponseType(typeof(ResponseWrap<string[]>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<string[]>))]
	public async Task<ResponseWrap<string[]>> ValidateJob([FromRoute] string id)
	{
		return await InnerValidateJob(id);
	}

	/// <summary>
	///   Deletes a job by Id.
	/// </summary>
	/// <remarks>
	///   The response integer is the number of licensing database rows affected by delete processing. Zero indicates that the job was not found.
	/// </remarks>
	/// <param name="id">The Id of the job to read.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>int</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpDelete]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("{id}")]
	[ProducesResponseType(typeof(ResponseWrap<int>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<int>))]
	public async Task<ResponseWrap<int>> DeleteJob([FromRoute] string id)
	{
		return await InnerDeleteJob(id);
	}

	/// <summary>
	///   Disconnect a job from a user.
	/// </summary>
	/// <param name="JobId">The Id of the parent job.</param>
	/// <param name="userId">The Id of the child user.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>Job?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpGet]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("disconnect/{jobId}/user/{userId}")]
	[ProducesResponseType(typeof(ResponseWrap<Job?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<Job?>))]
	public async Task<ResponseWrap<Job?>> DisconnectJobChildUser([FromRoute] string JobId, [FromRoute] string userId)
	{
		return await InnerDisconnectJobChildUser(JobId, userId);
	}

	/// <summary>
	///   Connect a job to users.
	/// </summary>
	/// <param name="request">The request body contains a serialized <c>JoinsRequest</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>Job?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPost]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("connect/users")]
	[ProducesResponseType(typeof(ResponseWrap<Job?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<Job?>))]
	public async Task<ResponseWrap<Job?>> ConnectJobChildUsers([FromBody] JoinsRequest request)
	{
		return await InnerConnectJobChildUsers(request);
	}

	/// <summary>
	///   Replaces the full set of job to user connections.
	/// </summary>
	/// <param name="request">The request body contains a serialized <c>JoinsRequest</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>Job?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPost]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("replace/users")]
	[ProducesResponseType(typeof(ResponseWrap<Job?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<Job?>))]
	public async Task<ResponseWrap<Job?>> ReplaceJobChildUsers([FromBody] JoinsRequest request)
	{
		return await InnerReplaceJobChildUsers(request);
	}

	/// <summary>
	///   Compares licensing jobs against cloud containers.
	/// </summary>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>string</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpGet]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("compare")]
	[ProducesResponseType(typeof(ResponseWrap<string>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<string>))]
	public async Task<ResponseWrap<string>> CompareJobsAndContainers()
	{
		return await InnerCompareJobsAndContainers();
	}

	/// <summary>
	///   Creates a Job Container.
	/// </summary>
	/// <remarks>
	///   Creates an Azure container with a name corresponding to an existing licensing job and sets the public access level to Blobs. The container is created in the Storage Account that corresponds to the job's parent customer.
	/// </remarks>
	/// <param name="request">The request body contains a serialized <c>CreateJobContainerRequest</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>bool</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// <br/><br/><b>Response Codes</b><br/>
	/// <br/>• 1 – Job not found.
	/// <br/>• 2 – No parent customer Id.
	/// <br/>• 3 – Parent customer not found.
	/// <br/>• 4 – No customer storage key.
	/// <br/>• 5 – Failed to create container.
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPost]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("azure/container")]
	[ProducesResponseType(typeof(ResponseWrap<bool>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<bool>))]
	public async Task<ResponseWrap<bool>> CreateJobContainer([FromBody] CreateJobContainerRequest request)
	{
		return await InnerCreateJobContainer(request);
	}

}

partial class UserController
{
	/// <summary>
	///   Create a user.
	/// </summary>
	/// <remarks>
	///   These properties are ignored because they are internally generated by new user processing: <c>Id</c>, <c>Created</c>, <c>PassHash</c>, <c>Uid</c>, <c>Customers</c>, <c>Jobs</c>, <c>Realms</c>. All other property values are saved in the new user record.
	/// </remarks>
	/// <param name="user">The request body contains a serialized <c>User</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>UpsertResult&lt;User&gt;</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPost]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("create")]
	[ProducesResponseType(typeof(ResponseWrap<UpsertResult<User>>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<UpsertResult<User>>))]
	public async Task<ResponseWrap<UpsertResult<User>>> CreateUser([FromBody] User user)
	{
		return await InnerCreateUser(user);
	}

	/// <summary>
	///   Reads a user by Id.
	/// </summary>
	/// <remarks>
	///   The response <c>hasError</c> property will be true if the customer is not found.
	/// </remarks>
	/// <param name="id">The Id of the user to read.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>User?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpGet]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("read/{id}")]
	[ProducesResponseType(typeof(ResponseWrap<User?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<User?>))]
	public async Task<ResponseWrap<User?>> ReadUser([FromRoute] string id)
	{
		return await InnerReadUser(id);
	}

	/// <summary>
	///   Lists all users.
	/// </summary>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>User[]</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpGet]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("list")]
	[ProducesResponseType(typeof(ResponseWrap<User[]>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<User[]>))]
	public async Task<ResponseWrap<User[]>> ListUsers()
	{
		return await InnerListUsers();
	}

	/// <summary>
	///   Lists all users optionally filtered by realm Ids.
	/// </summary>
	/// <param name="request">The request body contains a serialized <c>IdFilterRequest</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>User[]</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPost]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("list")]
	[ProducesResponseType(typeof(ResponseWrap<User[]>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<User[]>))]
	public async Task<ResponseWrap<User[]>> ListUsers([FromBody] IdFilterRequest request)
	{
		return await InnerListUsers(request);
	}

	/// <summary>
	///   List users, optionally filtered by realms.
	/// </summary>
	/// <remarks>
	///   The returned array of lightweight <c>UserPick</c> objects can be used by clients to fill summary or pick lists of users.
	/// </remarks>
	/// <param name="request">The request body contains a serialized <c>IdFilterRequest</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>UserPick[]</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPost]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("list/picks")]
	[ProducesResponseType(typeof(ResponseWrap<UserPick[]>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<UserPick[]>))]
	public async Task<ResponseWrap<UserPick[]>> ListUserPicksForRealms([FromBody] IdFilterRequest request)
	{
		return await InnerListUserPicksForRealms(request);
	}

	/// <summary>
	///   Update a user.
	/// </summary>
	/// <remarks>
	///   The <c>Id</c> primary key property identifies the User record to be updated. These properties are ignored because they are internally generated by new user processing: <c>Created</c>, <c>PassHash</c>, <c>Uid</c>, <c>Customers</c>, <c>Jobs</c>, <c>Realms</c>. All other property values are updated in the user record.
	/// </remarks>
	/// <param name="user">The request body contains a serialized <c>User</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>UpsertResult&lt;User&gt;</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPut]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("")]
	[ProducesResponseType(typeof(ResponseWrap<UpsertResult<User>>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<UpsertResult<User>>))]
	public async Task<ResponseWrap<UpsertResult<User>>> UpsertUser([FromBody] User user)
	{
		return await InnerUpsertUser(user);
	}

	/// <summary>
	///   Deletes a user by Id.
	/// </summary>
	/// <remarks>
	///   The response integer is the number of licensing database rows affected by delete processing. Zero indicates that the user was not found.
	/// </remarks>
	/// <param name="id">The Id of the user to delete.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>int</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpDelete]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("{id}")]
	[ProducesResponseType(typeof(ResponseWrap<int>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<int>))]
	public async Task<ResponseWrap<int>> DeleteUser([FromRoute] string id)
	{
		return await InnerDeleteUser(id);
	}

	/// <summary>
	///   Disconnect a user from a customer.
	/// </summary>
	/// <param name="userId">The Id of the parent user.</param>
	/// <param name="customerId">The Id of the child customer.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>User?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpGet]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("disconnect/{userId}/customer/{customerId}")]
	[ProducesResponseType(typeof(ResponseWrap<User?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<User?>))]
	public async Task<ResponseWrap<User?>> DisconnectUserChildCustomer([FromRoute] string userId, [FromRoute] string customerId)
	{
		return await InnerDisconnectUserChildCustomer(userId, customerId);
	}

	/// <summary>
	///   Connects a user to customers.
	/// </summary>
	/// <param name="request">The request body contains a serialized <c>JoinsRequest</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>User?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPost]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("connect/customers")]
	[ProducesResponseType(typeof(ResponseWrap<User?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<User?>))]
	public async Task<ResponseWrap<User?>> ConnectUserChildCustomers([FromBody] JoinsRequest request)
	{
		return await InnerConnectUserChildCustomers(request);
	}

	/// <summary>
	///   Replaces user and customer joins.
	/// </summary>
	/// <param name="request">The request body contains a serialized <c>JoinsRequest</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>User?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPost]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("replace/customers")]
	[ProducesResponseType(typeof(ResponseWrap<User?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<User?>))]
	public async Task<ResponseWrap<User?>> ReplaceUserChildCustomers([FromBody] JoinsRequest request)
	{
		return await InnerReplaceUserChildCustomers(request);
	}

	/// <summary>
	///   Disconnect a user from a job.
	/// </summary>
	/// <param name="userId">The Id of the parent user.</param>
	/// <param name="jobId">The Id of the child job.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>User?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpGet]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("disconnect/{userId}/job/{jobId}")]
	[ProducesResponseType(typeof(ResponseWrap<User?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<User?>))]
	public async Task<ResponseWrap<User?>> DisconnectUserChildJob([FromRoute] string userId, [FromRoute] string jobId)
	{
		return await InnerDisconnectUserChildJob(userId, jobId);
	}

	/// <summary>
	///   Connects a user to jobs.
	/// </summary>
	/// <param name="request">The request body contains a serialized <c>JoinsRequest</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>User?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPost]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("connect/jobs")]
	[ProducesResponseType(typeof(ResponseWrap<User?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<User?>))]
	public async Task<ResponseWrap<User?>> ConnectUserChildJobs([FromBody] JoinsRequest request)
	{
		return await InnerConnectUserChildJobs(request);
	}

	/// <summary>
	///   Replaces user and job joins.
	/// </summary>
	/// <param name="request">The request body contains a serialized <c>JoinsRequest</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>User?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPost]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("replace/jobs")]
	[ProducesResponseType(typeof(ResponseWrap<User?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<User?>))]
	public async Task<ResponseWrap<User?>> ReplaceUserChildJobs([FromBody] JoinsRequest request)
	{
		return await InnerReplaceUserChildJobs(request);
	}

	/// <summary>
	///   Disconnect a user from a realm.
	/// </summary>
	/// <param name="userId">The Id of the parent user.</param>
	/// <param name="realmId">The Id of the child realm.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>User?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpGet]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("disconnect/{userId}/realm/{realmId}")]
	[ProducesResponseType(typeof(ResponseWrap<User?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<User?>))]
	public async Task<ResponseWrap<User?>> DisconnectUserChildRealm([FromRoute] string userId, [FromRoute] string realmId)
	{
		return await InnerDisconnectUserChildRealm(userId, realmId);
	}

	/// <summary>
	///   connects a user to realms.
	/// </summary>
	/// <param name="request">The request body contains a serialized <c>JoinsRequest</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>User?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPost]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("connect/realms")]
	[ProducesResponseType(typeof(ResponseWrap<User?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<User?>))]
	public async Task<ResponseWrap<User?>> ConnectUserChildRealms([FromBody] JoinsRequest request)
	{
		return await InnerConnectUserChildRealms(request);
	}

	/// <summary>
	///   Replaces all user to realm connections.
	/// </summary>
	/// <param name="request">The request body contains a serialized <c>JoinsRequest</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>User?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPost]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("replace/realms")]
	[ProducesResponseType(typeof(ResponseWrap<User?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<User?>))]
	public async Task<ResponseWrap<User?>> ReplaceUserChildRealms([FromBody] JoinsRequest request)
	{
		return await InnerReplaceUserChildRealms(request);
	}

	/// <summary>
	///   Changes a user's password.
	/// </summary>
	/// <param name="request">The request body contains a serialized <c>PasswordChangeRequest</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>int</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPost]
	[ApiExplorerSettings(IgnoreApi = true)]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("password/change")]
	[ProducesResponseType(typeof(ResponseWrap<int>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<int>))]
	public async Task<ResponseWrap<int>> PasswordChange([FromBody] PasswordChangeRequest request)
	{
		return await InnerPasswordChange(request);
	}

	/// <summary>
	///   Sends a change password request through two-factor-authentication.
	/// </summary>
	/// <remarks>
	///   Attempts to send a change password request via email so it can be verified by two-factor-authentication and then processed by an external service.
	/// </remarks>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>string?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// <br/><br/><b>Response Codes</b><br/>
	/// <br/>• 1 – User not found.
	/// <br/>• 11 – User has no email address.
	/// <br/>• 12 – Email configuration values undefined.
	/// <br/>• 13 – Storage configuration values undefined.
	/// <br/>• 14 – Email send failed.
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPost]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("plea/password/{userId}")]
	[ProducesResponseType(typeof(ResponseWrap<string?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<string?>))]
	public async Task<ResponseWrap<string?>> PasswordChangePlea([FromRoute] string userId)
	{
		return await InnerPasswordChangePlea(userId);
	}

	/// <summary>
	///   Gets a plea.
	/// </summary>
	/// <remarks>
	///   Applications can use this endpoint to retreive a previously registered plea, validate it, then perform whatever processing is required.
	/// </remarks>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>PleaItem?</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpGet]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("plea/{id}")]
	[ProducesResponseType(typeof(ResponseWrap<PleaItem?>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<PleaItem?>))]
	public async Task<ResponseWrap<PleaItem?>> GetPlea([FromRoute] string id)
	{
		return await InnerGetPlea(id);
	}

	/// <summary>
	///   Updates specific user account values.
	/// </summary>
	/// <param name="request">The request body contains a serialized <c>UpdateAccountRequest</c>.</param>
	/// <response code="200">
	///   The web service call succeeded. The response body contains a serialized <c>ResponseWrap</c>.
	///   If the <c>hasError</c> property is <b>false</b> then the <c>data</c> property contains a serialized <c>int</c>.
	///   <i>For more information see: <a href="https://github.com/redcentre/Carbon.Examples.Licensing.WebService" target="_blank">Carbon Example Licensing Web Service</a>.</i>
	/// </response>
	[GeneratedCode("TextTemplatingService", "17.0.0.0")]
	[HttpPut]
	[TypeFilter(typeof(AuthCheckerAttribute))]
	[Route("account")]
	[ProducesResponseType(typeof(ResponseWrap<int>), StatusCodes.Status200OK)]
	[SwaggerResponse((int)HttpStatusCode.OK, "The request succeeded.", typeof(ResponseWrap<int>))]
	public async Task<ResponseWrap<int>> UpdateAccount([FromBody] UpdateAccountRequest request)
	{
		return await InnerUpdateAccount(request);
	}

}
